namespace Catering.UserService.Application.Dtos;

public sealed record UserDto(
    Guid Id,
    string Email,
    string FirstName,
    string LastName,
    string TcIdentityNumber,
    string PhoneNumber,
    DateOnly? BirthDate,
    string? Address,
    string? ProfilePictureUrl,
    Guid DepartmentId,
    string DepartmentName,
    Guid PositionId,
    string PositionName,
    Guid? CenterId,
    DateOnly HireDate,
    DateOnly? TerminationDate,
    string Status,
    string Role,
    bool HasDisability,
    string? DisabilityDescription,
    decimal? SalaryCeiling,
    string? Notes,
    bool PasswordRegistered,
    DateTimeOffset? LastLoginAt,
    DateTimeOffset CreatedAt);
